### ISSUE TITLE
Due and New calculated incorrectly after 2.1.4

### ISSUE THREAD

**Issue by keith555** [C9HDN/anki-deck-stats#8]
I have some decks which I have suspended by putting them in an Options Group with New Cards=0. The cards in these decks are being listed as Due/New. Edit:  I'm not sure if the bug was introduced with the 2.1.4 Anki update or the recently released updated to this add-on. I installed them both at the same time.

**Comment by teaqu** [comment]
Hi Keith. Thanks for reporting! Should now be fixed.

**Comment by keith555** [comment]
Hi. Thanks for that. Unfortunately, I'm still experiencing the problem.

**Comment by teaqu** [comment]
Hi Keith, what version of anki are you using?

**Comment by teaqu** [comment]
Should be good now.

**Comment by keith555** [comment]
> Should be good now.

That's fixed it now. Thanks for your help.
